---
- name: Pip install autorandr
  pip:
    -name: autorandr

- name: Create config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/autorandr"
    state: directory

- name: Copy postswitch script
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/autorandr/postswitch"
    src: "postswitch"

- name: Copy predetect script
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/autorandr/predetect"
    src: "predetect"

- name: Copy laptop configuration
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/autorandr/laptop"
    src: "laptop/"

- name: Copy homeoffice configuration
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/autorandr/home"
    src: "home/"

