---
- name: Install
  ansible.builtin.package:
    name:
      - vifm
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/vifm"
    state: directory

- name: Copy configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/vifm/vifmrc"
    src: "vifmrc"

- name: Colorscheme folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/vifm/colors"
    state: directory

- name: Copy colorscheme folder
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/vifm/colors"
    src: "colors/"

- name: Scripts folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/vifm/scripts"
    state: directory

- name: Copy script vifmimg
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/vifm/scripts/vifmimg"
    src: "scripts/vifmimg"

- name: Copy script vifmrun
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/vifm/scripts/vifmrun"
    src: "scripts/vifmrun"
