---
- name: Install xorg packages
  become: yes
  package:
    name:
      - xorg-x11-server-Xorg
      - xorg-x11-drv-intel
      - xorg-x11-xinit
      - xorg-x11-xinit-session
      - xorg-x11-server-common
      - xorg-x11-xauth
      - xmodmap
      - xrandr
      - xrdb
      - xset
      - xss-lock
    state: present

- name: Copy xinitrc
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.xinitrc"
    src: ".xinitrc"

- name: Copy xprofile
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.xprofile"
    src: ".xprofile"

- name: Copy Xmodmap
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xmodmap"
    src: ".Xmodmap"

- name: Copy Xresources
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xresources"
    src: ".Xresources"

- name: Copy Xresources-homeoffice
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xresources-homeoffice"
    src: ".Xresources-homeoffice"

- name: Screenlayout folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.screenlayout"
    state: directory

- name: Screenlayout laptop
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.screenlayout/laptop.sh"
    src: "laptop.sh"

- name: Screenlayout homeoffice open
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.screenlayout/homeoffice_open.sh"
    src: "homeoffice_open.sh"

- name: Screenlayout homeoffice closed
  ansible.builtin.copy:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.screenlayout/homeoffice_closed.sh"
    src: "homeoffice_closed.sh"

