---
- name: Install xorg packages
  become: yes
  package:
    name:
      - xorg-x11-server-Xorg
      - xorg-x11-drv-intel
      - xorg-x11-xinit
      - xorg-x11-xinit-session
      - xorg-x11-server-common
      - xorg-x11-xauth
      - xmodmap
      - xrandr
      - xrdb
      - xset
      - xss-lock
    state: present

- name: Copy xinitrc
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.xinitrc"
    src: ".xinitrc"

- name: Copy xprofile
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.xprofile"
    src: ".xprofile"

- name: Copy Xmodmap
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xmodmap"
    src: ".Xmodmap"

- name: Copy Xresources
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xresources"
    src: ".Xresources"

- name: Copy Xresources-homeoffice
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xresources-homeoffice"
    src: ".Xresources-homeoffice"
