---
- name: Local icon folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.icons"
    state: directory

- name: Copy icons ArchLabs-Dark
  ansible.builtin.synchronize:
    dest: "{{ ansible_user_dir }}/.icons/ArchLabs-Dark"
    src: "ArchLabs-Dark/"
    checksum: true
