---
- name: Install programming languages
  ansible.builtin.packgage:
    name:
      - exa
      - tree
      - flameshot
      - wget
      - curl
      - blueman
      - zip
      - unzip
      - pavucontrol
      - playerctl
    state: latest
    become: yes

