---
- name: Install packages with default config
  ansible.builtin.package:
    name:
      - dnf-plugins-core
      - NetworkManager
      - NetworkManager-bluetooth
      - NetworkManager-wifi
      - NetworkManager-tui
      - NetworkManager-openconnect
      - alsa-utils
      - bluez
      - dbus
      - alsa-sof-firmware
      - pipewire
      - pipewire-alsa
      - pipewire-pulseaudio
      - pipewire-utils
      - wireplumber
      - volumeicon
      - exa
      - tree
      - flameshot
      - wget
      - curl
      - blueman
      - zip
      - unzip
      - pavucontrol
      - playerctl
      - okular
      - arandr
      - breeze-cursor-theme
      - deluge
      - fd-find
      - polkit-gnome
      - gnome-keyring
      - gnome-keyring-pam
      - light
      - mpv
      - network-manager-applet
      - nextcloud-client
      - openvpn
      - pcmanfm
      - setxkbmap
      - sxiv
      - terminus-fonts
      - terminus-fonts-console
      - tlp
      - tlp-rdw
      - xbacklight
      - xev
      - xmodmap
      - rsync
      - timeshift
      - akmod-nvidia
      - qemu-kvm
      - libvirt
      - virt-install
      - bridge-utils
      - virt-manager
      - virt-top
      - libguestfs-tools
      - guestfs-tools
      - {{ firmware_wifi }}
    state: latest
  become: yes

