---
- name: Install
  ansible.builtin.package:
    name:
      - qt5ct
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/qt5ct"
    state: directory

- name: Copy color configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/qt5ct/colors"
    src: "colors/"

- name: Copy configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/qt5ct/qt5ct.conf"
    src: "qt5ct.conf"

