---
- name: Install
  ansible.builtin.package:
    name:
      - kitty
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Copy configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    src: "kitty.conf"

