---
- name: Add repository
  ansible.builtin.yum_repository:
    name: brave-browser
    description: brave-browser repo
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
  become: yes

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  become: yes

- name: Install
  ansible.builtin.package:
    name:
      - brave-browser
    state: latest
  become: yes
     
