---
- name: Install
  ansible.builtin.package:
    name:
      - git
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory

- name: Copy configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/git/config"
    src: "config"

- name: Copy ignore
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/git/ignore"
    src: "ignore"

