---
- name: Install
  ansible.builtin.package:
    name:
      - dunst
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/dunst"
    state: directory

- name: Copy configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    src: "dunstrc"

