---
- name: Install awesome
  ansible.builtin.package:
    name:
      - awesome
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/awesome"
    state: directory

- name: Copy bling lib
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/awesome/rc.lua"
    src: "rc.lua"

- name: Copy bling lib
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/awesome/bling"
    src: "bling/"

- name: Copy freedesktop lib
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/awesome/freedesktop"
    src: "freedesktop/"

- name: Copy lain lib
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/awesome/lain"
    src: "lain/"

- name: Copy theme
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/awesome/themes"
    src: "themes/"
